### ISSUE TITLE
Peek into CEDAR

### ISSUE THREAD

**Issue by oolonek** [digital-botanical-gardens-initiative/dbgi-projects#4]
https://metadatacenter.org/

**Comment by oolonek** [comment]
https://github.com/metadatacenter

**Comment by oolonek** [comment]
https://metadatacenter.readthedocs.io/en/latest/

**Comment by rkuzya** [comment]
03.06.2024  
 Logged Into CEDAR
 Watched CEDAR video tutorials
  Joined CEDAR Mailing List

CEDAR website: https://metadatacenter.org/#about

CEDAR User Manual: https://metadatacenter.readthedocs.io/en/latest/user-overview/

Orientation for the CEDAR Workbench: https://more.metadatacenter.org/tools-training/orientation

**Comment by rkuzya** [comment]
04.06.2024

Went over the CEDAR Workbench Usage tutorial

    How to search for an available template
    How to populate (use) a template 
    How to edit a template

**Comment by rkuzya** [comment]
03.06.2024

    Logged Into CEDAR
    Watched CEDAR video tutorials
    Joined CEDAR Mailing List

CEDAR website: https://metadatacenter.org/#about

CEDAR User Manual: https://metadatacenter.readthedocs.io/en/latest/user-overview/

Orientation for the CEDAR Workbench: https://more.metadatacenter.org/tools-training/orientation

**Comment by rkuzya** [comment]
11.06.2024

Using CEDAR

1. Create an Account and Log In

    Sign Up: Go to the CEDAR website and sign up for an account.
    Log In: Once your account is created, log in with your credentials.

2. Familiarize Yourself with the Interface

    Dashboard: The dashboard is your central hub for accessing different features. Take some time to explore the layout and available options.

3. Create Metadata Templates

    Navigate to Templates: Go to the “Templates” section from the dashboard.
    Create New Template: Click on the option to create a new template.
    Design Template: Use the drag-and-drop interface to add fields, such as text boxes, drop-down lists, and checkboxes. Customize these fields to match your metadata requirements.
    Incorporate Ontologies: Integrate relevant ontologies and controlled vocabularies to ensure standardization. You can search and import these from within CEDAR.
    Save Template: Once you have designed your template, save it for future use.

4. Annotate Metadata Using Templates

    Select Template: Choose the appropriate template you created for annotating your data.
    Fill in Metadata: Input your metadata values into the fields defined in the template. Make sure to follow any guidelines or standards applicable to your data.
    Validate Metadata: Use the built-in validation tools to check for completeness and compliance with the template rules.

5. Collaborate and Share

    Share Templates and Metadata: CEDAR allows you to share your templates and annotated metadata with other users or groups. Use the sharing options to grant access to collaborators.
    Collaborative Editing: Multiple users can work on the same metadata template or annotation, facilitating teamwork and consistency.

6. Manage and Reuse Metadata

    Metadata Repository: Store and manage your metadata in the CEDAR repository.
    Search and Retrieve: Use the search functionality to find and retrieve specific metadata records or templates.
    Export Metadata: Export your metadata in various formats for use in other systems or for publication.

7. Integrate with Other Systems

    APIs: Utilize CEDAR’s APIs to integrate metadata management with other data systems and workflows in your organization.
    Interoperability: Ensure that your metadata complies with standards to enable interoperability with other tools and platforms.

8. Ensure Data Security and Privacy

    Access Controls: Set up appropriate access controls to protect your metadata. Define roles and permissions to manage who can view or edit your templates and metadata.
    Regular Backups: Ensure that your metadata is regularly backed up to prevent data loss.


Populating a template in the CEDAR tool refers to the process of filling out a pre-defined data template with specific information. CEDAR is designed to help researchers and scientists create, share, and reuse structured data templates for metadata annotation. Here's a step-by-step overview of what it means to populate a template in CEDAR:

    Template Selection: Choose or create a data template that fits the data you need to annotate. Templates in CEDAR are structured forms that define the fields and types of data required.

    Access the Template: Open the selected template within the CEDAR interface. The template will have various fields and sections that need to be filled out.

    Fill Out the Fields: Enter the relevant information into each field of the template. Fields might include text boxes, drop-down menus, checkboxes, date pickers, and more, depending on how the template is designed.

    Validation: Ensure that the data entered meets the specified requirements and constraints of each field. CEDAR may provide validation checks to ensure the data conforms to expected formats or values.

    Save or Submit: Once all required fields are filled and validated, save or submit the populated template. This might involve saving it to a database, exporting it in a particular format, or sharing it with other users or systems.

    Reuse and Share: Populated templates can be reused for similar data entries or shared with other researchers or systems that need access to the structured data.
